### ISSUE TITLE
Why exactly Zapperment uses Reason?

### ISSUE THREAD

**Issue by Catsvilles** [technology-ebay-de/zapperment#40]
Hi, cool project! :) So, I read the article and maybe I missed something but why exactly do we need Reason DAW? I mean, what are the functions of this DAW we have to rely on? If it is just the mixer we need, we could use one of the advanced Web Audio mixers available on Github. And then it would be super easy deployable on the server + low-cost hosting/processing for you since everything will happen in the browser/ frontend.

**Comment by pahund** [comment]
Hi Catsvilles, thanks for your question. I had actually put some thought into doing it the way you suggest, and decided against it.

Mixing (turning channels on/off) is just the beginning, my plan is to have the AI control the actual sound of the tracks by controlling synthesizer controls (filter cutoff, resonance, wave form), drum rhythm patterns, effect settings, perhaps later even chord progressions and melodies. The current prototype already does that to some extent.

The sound synthesis capabilities provided by the web audio API are quite limited compared to what a professional DAW like Reason is capable of. If Zapperment made music using the Web Audio API, it would always sound like a toy experiment, not like professionally produced music. 

My vision is to get DJs and musicians on the project to produce Zapperment tracks, they wouldn't want to use an amateurish web interface to create music, or write code, they would want to use the DAWs they are used to.

Then why Reason and not Live, Cubase, Logic, FL Studio or Studia One?

Well, mainly because I myself make music with Reason :-)

What I like about Reason is that its Combinator instruments allow you to build new "sound units" out of any and all of its instruments, providing a way to normalize the way the sound sources can be controlled through MIDI.
